### ISSUE TITLE
データ管理をrealmに切り替える

### ISSUE THREAD

**Issue by y-ogawara** [JunJun0128/SpiceKigen#3]
Realmを使おう！

今は fileOutputでデータを書き出しているので、DB(データベース)に切り替える

データベースにするメリット
データの追加、編集、削除が簡単
データを検索することが出来る
ソートが出来る
早い！！！！！

順序としては
* Realmの使い方を勉強する
* SpiceのDB構造を考える
* Spiceに実装する

**Comment by TaigaNatto** [comment]
Realmでの1対多の関係の記述について
https://qiita.com/boohbah/items/b515a16aa0034f622a85
